
spring:
  profiles: local
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/jpashop
    driver-class-name:  org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
 #       show-sql: true


logging:
  level:
  org.hibernate.SQL: debug

